#include <math.h>
#include <Wire.h>
#include <Adafruit_MPU6050.h>
#include <Adafruit_BMP280.h>
#include <Adafruit_Sensor.h>
#include <PID_v1_bc.h>
#include <WiFi.h>
#include <WebServer.h>

// ────────────────────────────────────────────────────────────────
// PIN DEFINITIONS
// ────────────────────────────────────────────────────────────────
#define ESC1 12 // Front-left motor (X configuration) (CW)
#define ESC2 19 // Front-right motor (CCW)
#define ESC3 27 // Rear-right motor (CW)
#define ESC4 14 // Rear-left motor (CCW)

#define CH_ROLL 32
#define CH_PITCH 33
#define CH_THROTTLE 34
#define CH_YAW 35
#define CH_ARM 25 // Arm/disarm switch
#define CH_AUX 26 // Altitude hold toggle

#define BAT_ADC_PIN 36 // Battery voltage divider
#define BUZZER_PIN 13 // Buzzer

#define LED_ARMED 15 // Green – Armed status
#define LED_LOWBAT 2 // Red – Low battery / cutoff
#define LED_ALTHOLD 4 // Blue – Altitude hold active
#define LED_FAILSAFE 16 // Yellow – Receiver failsafe

// ────────────────────────────────────────────────────────────────
// CONSTANTS
// ────────────────────────────────────────────────────────────────
#define VDIV_M 3.672f
#define VDIV_C 1.974f
#define LOW_VOLT_CUTOFF 9.3f
#define VOLT_WARNING 10.2f
#define FAILSAFE_TIMEOUT_MS 500
#define GRAVITY_CON 9.81f
#define LOOP_INTERVAL_MS 5

// ── USER CONFIGURATION (WiFi AP settings) ───────────────────────
#define WIFI_SSID "QuadTelemetry" // ← change before public use
#define WIFI_PASSWORD "flysafe123" // ← change before public use

// ── HARD IMU OFFSETS ──────────────────────────────────
// Generated by calibration tool
// 3 runs x 500 samples  |  Gyro dev: 0.000140  Accel dev: 0.002320
// Remeasure if IMU is remounted, replaced, or readings
// show consistent non-zero pitch/roll at rest.
// Gyro units: rad/s    Accel units: m/s²
#define GYRO_OFFSET_X -0.028283f
#define GYRO_OFFSET_Y +0.005112f
#define GYRO_OFFSET_Z +0.005862f

#define ACCEL_OFFSET_X +0.142248f
#define ACCEL_OFFSET_Y -0.016234f
#define ACCEL_OFFSET_Z +0.541555f // raw mean - gravity

// ── SOFTWARE TRIM ────────────────────────────────────────────────
// Compensates for fixed mechanical offsets (battery position etc.)
// Adjust PITCH_TRIM in 0.5° steps until hover is level.
// Positive PITCH_TRIM = nose-up correction (forward battery)
#define PITCH_TRIM 2.0f // degrees
#define ROLL_TRIM 0.0f // degrees

// ────────────────────────────────────────────────────────────────
// GLOBAL STATE VARIABLES
// ────────────────────────────────────────────────────────────────
Adafruit_MPU6050 mpu;
Adafruit_BMP280 bmp;
WebServer server(80);

double rollSetpoint = 0, rollInput, rollOutput;
double pitchSetpoint = 0, pitchInput, pitchOutput;
double yawRateSetpoint = 0, yawRateInput, yawRateOutput;
double altSetpoint = 0.5;
double altInput, altOutput;

PID pidRoll (&rollInput, &rollOutput, &rollSetpoint, 2.5, 0.02, 0.8, DIRECT);
PID pidPitch (&pitchInput, &pitchOutput, &pitchSetpoint, 2.5, 0.02, 0.8, DIRECT);
PID pidYawRate (&yawRateInput, &yawRateOutput, &yawRateSetpoint, 3.5, 0.02, 0.1, DIRECT);
PID pidAlt (&altInput, &altOutput, &altSetpoint, 2.0, 0.15, 1.0, DIRECT);
double originalAltKi = 0;

float gyroOffsetX = 0, gyroOffsetY = 0, gyroOffsetZ = 0;
float accelOffsetX = 0, accelOffsetY = 0, accelOffsetZ = 0;
float baroOffset = 0.0f;

float roll = 0, pitch = 0, yawRate = 0;
float height = 0, velocity = 0;
float gyroRollRate = 0, gyroPitchRate = 0;
float accelPitch = 0, accelRoll = 0;
float accelX = 0, accelY = 0, accelZ = 0;
float baroAlt = 0;

unsigned long prevTime = 0;
unsigned long lastValidSignalTime = 0;
uint16_t pwmRoll = 0, pwmPitch = 0, pwmThrottle = 0;
uint16_t pwmYaw = 0, pwmArm = 0, pwmAux = 0;

float rcRoll = 0, rcPitch = 0, rcYawRate = 0, rcThrottle = 0;

const float seaLevel = 1013.25f;
const float GYRO_SCALE = (180.0f / M_PI); // rad/s → deg/s
const float ADC_TO_VBAT = (3.3f / 4095.0f) * VDIV_M;
const float motorMin[4] = {1000, 1040, 1050, 1070}; // Tune these for your motors
const float motorMax = 2000.0f; // Same for all (full power)

struct BuzzerState {
  bool active = false;
  int beepsRemaining = 0;
  int frequency = 0;
  int duration_ms = 0;
  int pause_ms = 150;
  bool isTone = false;
  unsigned long lastToggle = 0;
  bool continuous = false;
  uint8_t priority = 0;
};

BuzzerState buzzer;

// Mutex for shared data between cores:
SemaphoreHandle_t dataMutex;
SemaphoreHandle_t rcMutex;

// Shared RC values — written by Core 0 rcTask, read by Core 1 flight loop
volatile uint16_t sharedPwmRoll = 1500;
volatile uint16_t sharedPwmPitch = 1500;
volatile uint16_t sharedPwmThrottle = 1000;
volatile uint16_t sharedPwmYaw = 1500;
volatile uint16_t sharedPwmArm = 1000;
volatile uint16_t sharedPwmAux = 1000;
volatile unsigned long sharedLastValidSignal = 0;

// Runtime debug toggle — controlled via HTTP /debug endpoint
volatile bool debugOutputEnabled = false; // off by default for flight

// Volatile — written outside dataMutex, read inside it in handleData()
// volatile prevents compiler reordering across the mutex barrier
volatile float vbat = 0.0f;
volatile float temperature = 0.0f;
volatile bool armed = false;
volatile bool altitudeHoldEnabled = false;
volatile bool receiverFailsafeActive = false;
volatile bool lowBatCutoff = false;
volatile bool lowBatWarning = false;
volatile uint16_t m1, m2, m3, m4;

// ── Boot orientation check ───────────────────────────────────────
enum class BootOrientation {
  LEVEL, // within ±15° on both axes — safe to fly
  TILTED, // 15°–60° — warn, recoverable without reboot
  ON_SIDE, // >60° — seriously misoriented
  INVERTED // accelZ negative — upside down
};

volatile bool orientationClearToFly = false;

const float alpha = 0.98f;
const float alpha_inv = 1.0f - alpha;

// Global dt (updated every loop iteration)
float global_dt = 0.0f;

// ── FORWARD DECLARATIONS ─────────────────────────────────────────
void handleRoot();
void handleData();
void calibrateBarometer();
BootOrientation checkBootOrientation(float &initialPitch, float &initialRoll);
void reEstimateAttitude();
void buzzerAlert(int count, int duration_ms, int freq = 1200, int pause_ms = 150, uint8_t priority = 0);
void buzzerAlertContinuous(int freq = 800, int duration_ms = 200, int pause_ms = 100, uint8_t priority = 0);
void buzzerStop();
void updateBuzzer();
void stopMotors();
void writeESC(uint8_t pin, uint16_t us);

// ────────────────────────────────────────────────────────────────
// SETUP
// ────────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(115200);
  Wire.begin();

  initPins();

  Serial.println("Starting Barometer calibration...");

  initSensors();
  calibrateAllSensors();

  initReceiver();
  initESCs();
  initPIDs();
  initHTTPTelemetry();

  Serial.println("Quad ready. Connect to WiFi: QuadTelemetry / flysafe123");
  Serial.println("Open browser at IP shown below for live telemetry.");
  Serial.println("Bind FS-i6. CH6 = altitude hold.");
  delay(2000);

  unsigned long startTime = millis();
  lastValidSignalTime = startTime;
  prevTime = startTime;
}

// ────────────────────────────────────────────────────────────────
// MAIN LOOP
// ────────────────────────────────────────────────────────────────
void loop() {
  unsigned long now = millis();
  unsigned long elapsed = now - prevTime;
  if (elapsed < LOOP_INTERVAL_MS) return;
  prevTime = now; // ← set at guard, not after sensors

  readReceiver();
  checkReceiverFailsafe();
  updateArmingAndHoldMode();
  checkBatteryVoltage();
  updateBuzzer();

  if (!armed) {
    stopMotors();
    updateLEDs();
    return;
  }

  readSensors();

  // elapsed is the true loop period — sensor read time cancels out exactly
  xSemaphoreTake(dataMutex, portMAX_DELAY);
  global_dt = elapsed / 1000.0f;

  rollSetpoint = rcRoll + ROLL_TRIM;
  pitchSetpoint = -rcPitch + PITCH_TRIM; // negative: forward stick = nose down - PITCH_TRIM corrects fixed battery offset
  yawRateSetpoint = rcYawRate;

  if (!altitudeHoldEnabled) {
    const float track_alpha = 0.01f;
    altSetpoint = track_alpha * height + (1.0f - track_alpha) * altSetpoint;
  }

  float cr, cp, sr, sp;
  fuseAttitude(global_dt, cr, cp, sr, sp);
  fuseAltitude(global_dt, cr, cp, sr, sp);
  runPIDs();
  xSemaphoreGive(dataMutex);

  mixAndWriteMotors();
  updateLEDs();
  debugOutput();
}

// ────────────────────────────────────────────────────────────────
// INITIALIZATION FUNCTIONS
// ────────────────────────────────────────────────────────────────
void initPins() {
  pinMode(BUZZER_PIN, OUTPUT);
  digitalWrite(BUZZER_PIN, LOW);

  pinMode(LED_ARMED, OUTPUT);
  pinMode(LED_LOWBAT, OUTPUT);
  pinMode(LED_ALTHOLD, OUTPUT);
  pinMode(LED_FAILSAFE, OUTPUT);
  digitalWrite(LED_ARMED, LOW);
  digitalWrite(LED_LOWBAT, LOW);
  digitalWrite(LED_ALTHOLD, LOW);
  digitalWrite(LED_FAILSAFE, LOW);

  analogReadResolution(12);
  analogSetAttenuation(ADC_11db);
  pinMode(BAT_ADC_PIN, INPUT);
}

void initSensors() {
  if (!mpu.begin()) {
    Serial.println("MPU6050 failed!");
    while (1) delay(10);
  }
  mpu.setAccelerometerRange(MPU6050_RANGE_8_G);
  mpu.setGyroRange(MPU6050_RANGE_500_DEG);
  mpu.setFilterBandwidth(MPU6050_BAND_44_HZ);

  if (!bmp.begin(0x76)) {
    Serial.println("BMP280 failed!");
    while (1) delay(10);
  }
  bmp.setSampling(Adafruit_BMP280::MODE_NORMAL,
                  Adafruit_BMP280::SAMPLING_X2,
                  Adafruit_BMP280::SAMPLING_X16,
                  Adafruit_BMP280::FILTER_X16,
                  Adafruit_BMP280::STANDBY_MS_63);

  Wire.setClock(400000);
}

void initReceiver() {
  pinMode(CH_ROLL, INPUT);
  pinMode(CH_PITCH, INPUT);
  pinMode(CH_THROTTLE, INPUT);
  pinMode(CH_YAW, INPUT);
  pinMode(CH_ARM, INPUT);
  pinMode(CH_AUX, INPUT);
}

void initESCs() {
  const uint32_t PWM_FREQ = 50;
  const uint8_t PWM_RES = 16;

  ledcAttach(ESC1, PWM_FREQ, PWM_RES);
  ledcAttach(ESC2, PWM_FREQ, PWM_RES);
  ledcAttach(ESC3, PWM_FREQ, PWM_RES);
  ledcAttach(ESC4, PWM_FREQ, PWM_RES);

  writeESC(ESC1, 1000);
  writeESC(ESC2, 1000);
  writeESC(ESC3, 1000);
  writeESC(ESC4, 1000);
  delay(3500);
}

void initPIDs() {
  pidRoll.SetMode(AUTOMATIC); pidRoll.SetOutputLimits(-250, 250); pidRoll.SetSampleTime(LOOP_INTERVAL_MS);
  pidPitch.SetMode(AUTOMATIC); pidPitch.SetOutputLimits(-250, 250); pidPitch.SetSampleTime(LOOP_INTERVAL_MS);
  pidYawRate.SetMode(AUTOMATIC); pidYawRate.SetOutputLimits(-180, 180); pidYawRate.SetSampleTime(LOOP_INTERVAL_MS);
  pidAlt.SetMode(AUTOMATIC); pidAlt.SetOutputLimits(-300, 400); pidAlt.SetSampleTime(LOOP_INTERVAL_MS);
  originalAltKi = pidAlt.GetKi();
}

void initHTTPTelemetry() {
  WiFi.softAP(WIFI_SSID, WIFI_PASSWORD);
  IPAddress IP = WiFi.softAPIP();

  Serial.println("WiFi AP started");
  Serial.print("SSID: "); Serial.println(WIFI_SSID);
  Serial.print("Password: "); Serial.println(WIFI_PASSWORD);
  Serial.print("Open browser at: http://"); Serial.println(IP);

  server.on("/", handleRoot);
  server.on("/data", handleData);

  // Debug toggle endpoints
  server.on("/debug/on", []() {
    debugOutputEnabled = true;
    server.send(200, "application/json", "{\"debug\":true}");
    Serial.println("Debug output ENABLED via HTTP");
  });
  server.on("/debug/off", []() {
    debugOutputEnabled = false;
    server.send(200, "application/json", "{\"debug\":false}");
    Serial.println("Debug output DISABLED via HTTP");
  });
  server.on("/debug", []() {
    char buf[32];
    snprintf(buf, sizeof(buf), "{\"debug\":%s}",
             debugOutputEnabled ? "true" : "false");
    server.send(200, "application/json", buf);
  });

  server.begin();
  Serial.println("HTTP telemetry server started.");

  dataMutex = xSemaphoreCreateMutex();
  rcMutex = xSemaphoreCreateMutex();

  // RC task — Core 0, priority 2
  // Throttle read first so sharedLastValidSignal is updated immediately —
  // reduces failsafe detection delay from ~26ms to ~1.5ms typical.
  // vTaskDelay(1) between each channel gives WiFiTask ~23% CPU share.
  xTaskCreatePinnedToCore(
    [](void*) {
      const uint32_t timeout_us = 30000;

      // Per-channel previous values for spike rejection
      uint16_t prevT = 1000;
      uint16_t prevR = 1500;
      uint16_t prevP = 1500;
      uint16_t prevY = 1500;
      uint16_t prevArm = 1000;
      uint16_t prevAux = 1000;

      // Anything larger is a measurement spike — discard and keep previous value.
      const uint16_t SPIKE_THRESHOLD = 600;

      // Switch channels (ARM, AUX): no spike threshold —
      // they legitimately flip full range in one frame

      while (1) {
        uint16_t r, p, t, y, arm, aux;

        // ── Throttle first — update signal timestamp immediately ──
        t = pulseIn(CH_THROTTLE, HIGH, timeout_us);
        if (t > 900 && t < 2100)
          sharedLastValidSignal = millis();
        if (t == 0 || t < 800 || t > 2200)
          t = prevT; // out of range → keep previous
        else if (abs((int)t - (int)prevT) > SPIKE_THRESHOLD)
          t = prevT; // spike → keep previous
        else
          prevT = t; // valid → update previous
        vTaskDelay(1);

        // ── Remaining channels ──
        r = pulseIn(CH_ROLL, HIGH, timeout_us);
        if (r < 800 || r > 2200)
          r = prevR;
        else if (abs((int)r - (int)prevR) > SPIKE_THRESHOLD)
          r = prevR;
        else
          prevR = r;
        vTaskDelay(1);

        p = pulseIn(CH_PITCH, HIGH, timeout_us);
        if (p < 800 || p > 2200)
          p = prevP;
        else if (abs((int)p - (int)prevP) > SPIKE_THRESHOLD)
          p = prevP;
        else
          prevP = p;
        vTaskDelay(1);

        y = pulseIn(CH_YAW, HIGH, timeout_us);
        if (y < 800 || y > 2200)
          y = prevY;
        else if (abs((int)y - (int)prevY) > SPIKE_THRESHOLD)
          y = prevY;
        else
          prevY = y;
        vTaskDelay(1);

        // ── Arm switch — range check only, no spike threshold ──
        // Legitimate flip covers full range in one frame
        arm = pulseIn(CH_ARM, HIGH, timeout_us);
        if (arm < 800 || arm > 2200)
          arm = prevArm;
        else
          prevArm = arm;
        vTaskDelay(1);

        // ── Aux switch — range check only, no spike threshold ──
        aux = pulseIn(CH_AUX, HIGH, timeout_us);
        if (aux < 800 || aux > 2200)
          aux = prevAux;
        else
          prevAux = aux;
        vTaskDelay(1);

        // ── Full snapshot write at end of frame ──
        xSemaphoreTake(rcMutex, portMAX_DELAY);
        sharedPwmRoll= r;
        sharedPwmPitch = p;
        sharedPwmThrottle = t;
        sharedPwmYaw = y;
        sharedPwmArm = arm;
        sharedPwmAux = aux;
        xSemaphoreGive(rcMutex);
      }
    },
    "RCTask",
    2048,
    nullptr,
    2,
    nullptr,
    0
  );

  // WiFi task — Core 0, priority 1
  // Gets CPU during the 6x vTaskDelay(1) windows per RC frame (~23% share)
  xTaskCreatePinnedToCore(
    [](void*) {
      while (1) {
        server.handleClient();
        vTaskDelay(1);
      }
    },
    "WiFiTask",
    8192,
    nullptr,
    1, // priority 1 — yields to RCTask
    nullptr,
    0 // Core 0
  );
}

void calibrateAllSensors() {
  // Apply hard offsets — no runtime measurement needed
  gyroOffsetX = GYRO_OFFSET_X;
  gyroOffsetY = GYRO_OFFSET_Y;
  gyroOffsetZ = GYRO_OFFSET_Z;
  accelOffsetX = ACCEL_OFFSET_X;
  accelOffsetY = ACCEL_OFFSET_Y;
  accelOffsetZ = ACCEL_OFFSET_Z;

  Serial.println("Hard IMU offsets applied.");
  Serial.printf("Gyro  offsets: X=%.6f Y=%.6f Z=%.6f rad/s\n",
                gyroOffsetX, gyroOffsetY, gyroOffsetZ);
  Serial.printf("Accel offsets: X=%.6f Y=%.6f Z=%.6f m/s²\n",
                accelOffsetX, accelOffsetY, accelOffsetZ);

  // Check orientation and seed filter with measured angles
  float initialPitch = 0.0f;
  float initialRoll = 0.0f;
  BootOrientation orientation = checkBootOrientation(initialPitch, initialRoll);

  // Seed complementary filter — eliminates ~1.25s convergence delay at boot
  pitch = initialPitch;
  roll = initialRoll;
  Serial.printf("Filter seeded — Pitch: %.2f°  Roll: %.2f°\n", pitch, roll);

  // Barometer always calibrated at runtime — pressure varies with weather
  calibrateBarometer();
  Serial.printf("Baro offset: %.2f m\n", baroOffset);

  if (orientation != BootOrientation::LEVEL) {
    Serial.println("WARNING: Drone not level at boot — arming blocked until level.");
  }
}

// ────────────────────────────────────────────────────────────────
// CALIBRATION FUNCTIONS
// ────────────────────────────────────────────────────────────────
void calibrateBarometer() {
  const int numSamples = 100;
  float sumAlt = 0.0f;

  Serial.print("Calibrating barometer... ");

  for (int i = 0; i < numSamples; i++) {
    float alt = bmp.readAltitude(seaLevel);
    sumAlt += alt;
    delay(10);
  }

  baroOffset = sumAlt / numSamples;
  tone(BUZZER_PIN, 1800, 200);
}

BootOrientation checkBootOrientation(float &initialPitch, float &initialRoll) {
  const int numSamples = 100;
  float sumAx = 0, sumAy = 0, sumAz = 0;

  Serial.println("Checking boot orientation...");

  for (int i = 0; i < numSamples; i++) {
    sensors_event_t a, g, temp;
    mpu.getEvent(&a, &g, &temp);
    sumAx += a.acceleration.x - accelOffsetX;
    sumAy += a.acceleration.y - accelOffsetY;
    sumAz += a.acceleration.z - accelOffsetZ;
    delay(5);
  }

  float ax = sumAx / numSamples;
  float ay = sumAy / numSamples;
  float az = sumAz / numSamples;

  // Same formula as readSensors() — consistent with filter
  initialPitch = atan2f(ay, az) * GYRO_SCALE;
  initialRoll = -atan2f(ax, sqrtf(ay * ay + az * az)) * GYRO_SCALE;
  float tiltAngle = sqrtf(initialPitch * initialPitch + initialRoll * initialRoll);

  Serial.printf("Boot orientation — Pitch: %.2f°  Roll: %.2f°  Tilt: %.2f°\n",
                initialPitch, initialRoll, tiltAngle);

  BootOrientation result;

  if (az < 0.0f) {
    result = BootOrientation::INVERTED;
    Serial.println("ORIENTATION: INVERTED — flip drone right side up before arming");

  } else if (tiltAngle > 60.0f) {
    result = BootOrientation::ON_SIDE;
    Serial.printf("ORIENTATION: ON SIDE (%.1f°) — place drone flat before arming\n",
                  tiltAngle);

  } else if (tiltAngle > 15.0f) {
    result = BootOrientation::TILTED;
    Serial.printf("ORIENTATION: TILTED (%.1f°) — level the drone before arming\n",
                  tiltAngle);

  } else {
    result = BootOrientation::LEVEL;
    Serial.printf("ORIENTATION: LEVEL (%.1f°) — OK to fly\n", tiltAngle);
    orientationClearToFly = true;
  }

  switch (result) {
    case BootOrientation::LEVEL:
      tone(BUZZER_PIN, 2000, 150); delay(200);
      tone(BUZZER_PIN, 2000, 150); delay(200);
      break;
    case BootOrientation::TILTED:
      tone(BUZZER_PIN, 1200, 200); delay(250);
      tone(BUZZER_PIN, 1200, 200); delay(250);
      tone(BUZZER_PIN, 1200, 200); delay(250);
      break;
    case BootOrientation::ON_SIDE:
      tone(BUZZER_PIN, 800, 300); delay(350);
      tone(BUZZER_PIN, 800, 300); delay(350);
      tone(BUZZER_PIN, 800, 300); delay(350);
      tone(BUZZER_PIN, 800, 300); delay(350);
      break;
    case BootOrientation::INVERTED:
      tone(BUZZER_PIN, 600, 1500);
      delay(1600);
      break;
  }

  return result;
}

void reEstimateAttitude() {
  const int numSamples = 20;  // ~6.3ms at 400kHz I2C — acceptable at disarm
  float sumAx = 0, sumAy = 0, sumAz = 0;

  for (int i = 0; i < numSamples; i++) {
    sensors_event_t a, g, temp;
    mpu.getEvent(&a, &g, &temp);
    sumAx += a.acceleration.x - accelOffsetX;
    sumAy += a.acceleration.y - accelOffsetY;
    sumAz += a.acceleration.z - accelOffsetZ;
  }

  float ax = sumAx / numSamples;
  float ay = sumAy / numSamples;
  float az = sumAz / numSamples;

  // Same formula as readSensors() and checkBootOrientation()
  float newPitch = atan2f(ay, az) * GYRO_SCALE;
  float newRoll  = -atan2f(ax, sqrtf(ay * ay + az * az)) * GYRO_SCALE;

  // Only reseed if drone is reasonably level — if it disarmed mid-flip
  // or landed on its side the accel reading is valid but seeding a
  // 90° angle into the filter would cause problems on next arm
  float tilt = sqrtf(newPitch * newPitch + newRoll * newRoll);
  if (tilt < 60.0f) {
    pitch = newPitch;
    roll  = newRoll;
    Serial.printf("Attitude re-estimated at disarm — Pitch: %.2f°  Roll: %.2f°\n",
                  pitch, roll);
  } else {
    Serial.printf("Disarm re-estimate skipped — tilt too large (%.1f°)\n", tilt);
  }
}

// ────────────────────────────────────────────────────────────────
// CORE FLIGHT FUNCTIONS
// ────────────────────────────────────────────────────────────────
void readReceiver() {
  xSemaphoreTake(rcMutex, portMAX_DELAY);
  pwmRoll = sharedPwmRoll;
  pwmPitch = sharedPwmPitch;
  pwmThrottle = sharedPwmThrottle;
  pwmYaw = sharedPwmYaw;
  pwmArm = sharedPwmArm;
  pwmAux = sharedPwmAux;
  lastValidSignalTime = sharedLastValidSignal;
  xSemaphoreGive(rcMutex);

  // Tighter angle limit in altitude hold — preserves thrust headroom and
  // altitude estimate reliability. cos(25°)=0.906 vs cos(45°)=0.707.
  float angleLimit = altitudeHoldEnabled ? 25.0f : 45.0f;

  rcRoll = constrain((pwmRoll - 1500) / 500.0f * angleLimit, -angleLimit, angleLimit);
  rcPitch = constrain((pwmPitch - 1500) / 500.0f * angleLimit, -angleLimit, angleLimit);
  rcYawRate = constrain((pwmYaw - 1500) / 500.0f * 220.0f, -220.0f, 220.0f);
  rcThrottle = constrain((pwmThrottle - 1000) / 1000.0f * 1000.0f, 0.0f, 1000.0f);
}

void readSensors() {
  sensors_event_t a, g, temp;
  mpu.getEvent(&a, &g, &temp);

  // Body frame: X = right, Y = forward, Z = up
  // Right-hand rule conventions:
  // Positive pitch = nose up (rotation about +X)
  // Positive roll = right side down (rotation about +Y)
  // Positive yaw = right to left (rotation about +Z)

  gyroPitchRate = g.gyro.x - gyroOffsetX; // RHR about +X: +ve = nose up
  gyroRollRate = g.gyro.y - gyroOffsetY; // RHR about +Y: +ve = right side down
  yawRate = g.gyro.z - gyroOffsetZ; // RHR about +Z: +ve = right to left

  accelX = a.acceleration.x - accelOffsetX; // -g at 90° right-side-down
  accelY = a.acceleration.y - accelOffsetY; // +g at 90° nose-up
  accelZ = a.acceleration.z - accelOffsetZ; // +g when flat

  const float offsetX = 0.0f;
  const float offsetY = (27.0f / 1000.0f); // 27mm forward CoM
  const float offsetZ = (30.0f / 1000.0f); // 30mm above CoM

  float correctedAccelX = accelX + (gyroRollRate * gyroRollRate * offsetX);
  float correctedAccelY = accelY + (gyroPitchRate * gyroPitchRate * offsetY);
  float correctedAccelZ = accelZ + (gyroPitchRate * gyroPitchRate * offsetZ
                                  + gyroRollRate * gyroRollRate * offsetZ);

  // +ve = nose up: atan2(+g, 0) = +90° at 90° nose-up ✓
  accelPitch = atan2f(correctedAccelY, correctedAccelZ) * GYRO_SCALE;

  // +ve = right side down: -atan2(-g, 0) = +90° at 90° right-side-down ✓
  accelRoll = -atan2f(correctedAccelX,
                sqrtf(correctedAccelY * correctedAccelY
                    + correctedAccelZ * correctedAccelZ)) * GYRO_SCALE;

  accelX = correctedAccelX;
  accelY = correctedAccelY;
  accelZ = correctedAccelZ;

  baroAlt = bmp.readAltitude(seaLevel) - baroOffset;
  temperature = bmp.readTemperature();
}

// ────────────────────────────────────────────────────────────────
// FLIGHT LOGIC FUNCTIONS
// ────────────────────────────────────────────────────────────────
void checkReceiverFailsafe() {
  static int timeoutCounter = 0;
  static int goodSignalCounter = 0;
  const int TIMEOUT_CONFIRM_LOOPS = 5;
  const int GOOD_CONFIRM_LOOPS = 10;

  unsigned long now = millis();

  if (now - lastValidSignalTime > FAILSAFE_TIMEOUT_MS) {
    if (timeoutCounter < TIMEOUT_CONFIRM_LOOPS) timeoutCounter++;
    goodSignalCounter = 0;

    if (timeoutCounter >= TIMEOUT_CONFIRM_LOOPS && !receiverFailsafeActive) {
      receiverFailsafeActive = true;
      armed = false;
      altitudeHoldEnabled = false;
      stopMotors();
      reEstimateAttitude();
      Serial.println("FAILSAFE: No receiver signal - DISARMED!");
      buzzerAlert(4, 250, 1200, 150, 1);
    }
  } else {
    timeoutCounter = 0;
    if (goodSignalCounter < GOOD_CONFIRM_LOOPS) goodSignalCounter++;

    if (goodSignalCounter >= GOOD_CONFIRM_LOOPS && receiverFailsafeActive) {
      receiverFailsafeActive = false;
      Serial.println("Signal recovered - failsafe cleared");
    }
  }
}

void checkBatteryVoltage() {
  static unsigned long lastSampleTime = 0;
  static long sum = 0;
  static int sampleCount = 0;
  const int samples = 16;

  unsigned long now = millis();

  if (now - lastSampleTime >= 2) {
    lastSampleTime = now;
    int s = 0;
    for (int i = 0; i < 4; i++) s += analogRead(BAT_ADC_PIN);
    sum += s / 4;
    sampleCount++;
  }

  if (sampleCount >= samples) {
    vbat = (sum / (float)samples) * ADC_TO_VBAT + VDIV_C;

    sum = 0;
    sampleCount = 0;

    if (vbat < LOW_VOLT_CUTOFF && !lowBatCutoff) {
      lowBatCutoff = true;
      lowBatWarning = true;
      armed = false;
      altitudeHoldEnabled = false;
      stopMotors();
      reEstimateAttitude();
      Serial.printf("LOW VOLTAGE CUTOFF! VBat = %.2f V - LATCHED\n", vbat);
      buzzerStop();
      buzzerAlertContinuous(800, 250, 100, 2);
    } else if (lowBatCutoff && vbat > 9.6f) {
      lowBatCutoff = false;
      Serial.printf("Battery recovered: VBat = %.2f V - cutoff cleared\n", vbat);
      buzzerStop();
    } else if (vbat < VOLT_WARNING && !lowBatWarning) {
      lowBatWarning = true;
      Serial.printf("LOW BATTERY WARNING! VBat = %.2f V\n", vbat);
      buzzerAlert(2, 200, 1000, 150, 2);
    } else if (vbat >= VOLT_WARNING) {
      lowBatWarning = false;
    }
  }
}

void updateArmingAndHoldMode() {
  bool auxHigh = (pwmAux > 1500);
  bool armSwitchHigh = (pwmArm > 1500);
  bool throttleSafe = (rcThrottle < 200);

  // Re-check orientation each loop until cleared —
  // allows correction after boot without requiring reboot
  if (!orientationClearToFly) {
    static unsigned long lastOrientCheck = 0;
    unsigned long now_oc = millis();

    if (now_oc - lastOrientCheck >= 100) {
      lastOrientCheck = now_oc;

      const int numSamples = 5;
      float sumAx = 0, sumAy = 0, sumAz = 0;

      for (int i = 0; i < numSamples; i++) {
        sensors_event_t a, g, temp;
        mpu.getEvent(&a, &g, &temp);
        sumAx += a.acceleration.x - accelOffsetX;
        sumAy += a.acceleration.y - accelOffsetY;
        sumAz += a.acceleration.z - accelOffsetZ;
      }

      float ax = sumAx / numSamples;
      float ay = sumAy / numSamples;
      float az = sumAz / numSamples;

      float detectedPitch = atan2f(ay, az) * GYRO_SCALE;
      float detectedRoll = -atan2f(ax, sqrtf(ay * ay + az * az)) * GYRO_SCALE;
      float tiltAngle = sqrtf(detectedPitch * detectedPitch + detectedRoll * detectedRoll);

      if (az > 0.0f && tiltAngle <= 15.0f) {
        orientationClearToFly = true;
        pitch = detectedPitch;
        roll = detectedRoll;
        Serial.println("Orientation now level — arming enabled");
        tone(BUZZER_PIN, 2000, 150); delay(200);
        tone(BUZZER_PIN, 2000, 150);
      }
    }
  }

  // Altitude hold toggle (CH6 — independent of arming)
  if (auxHigh != altitudeHoldEnabled) {
    if (auxHigh) {
      pidAlt.SetTunings(pidAlt.GetKp(), 0.0, pidAlt.GetKd());
      const float feedforward_factor = 0.001f;
      altSetpoint = height + (rcThrottle - 500.0f) * feedforward_factor;
      Serial.println("Altitude hold ENABLED");
      buzzerAlert(1, 200, 1400, 50, 0);
    } else {
      pidAlt.SetTunings(pidAlt.GetKp(), originalAltKi, pidAlt.GetKd());
      Serial.println("Altitude hold DISABLED - integral restored");
    }
    altitudeHoldEnabled = auxHigh;
  }

  // Arming — requires orientation clear, throttle low, no battery cutoff
  bool canArm = armSwitchHigh && throttleSafe && !lowBatCutoff && orientationClearToFly;
  bool forceDisarm = !armSwitchHigh || lowBatCutoff;

  if (canArm && !armed) {
    armed = true;
    Serial.println("ARMED - Motors active");
    buzzerAlert(1, 300, 1200, 50, 0);
    digitalWrite(LED_ARMED, HIGH);
  }

  if (forceDisarm && armed) {
    armed = false;
    altitudeHoldEnabled = false;
    stopMotors();
    reEstimateAttitude();
    Serial.println("DISARMED - Motors stopped");
    buzzerAlert(1, 500, 600, 50, 0);
    digitalWrite(LED_ARMED, LOW);
  }
}

void fuseAttitude(float dt, float &cr_out, float &cp_out, float &sr_out, float &sp_out) {
  const float gyroScale_dt = GYRO_SCALE * dt;

  pitch = alpha * (pitch + gyroPitchRate * gyroScale_dt) + alpha_inv * accelPitch;
  roll = alpha * (roll + gyroRollRate * gyroScale_dt) + alpha_inv * accelRoll;

  float cr = cosf(roll * DEG_TO_RAD);
  float cp = cosf(pitch * DEG_TO_RAD);
  float sr = sinf(roll * DEG_TO_RAD);
  float sp = sinf(pitch * DEG_TO_RAD);

  cr_out = cr; cp_out = cp; sr_out = sr; sp_out = sp;
}

void fuseAltitude(float dt, float cr, float cp, float sr, float sp) {
  // R = Rx(pitch) · Ry(roll)
  // World-up row of R: [-sr*cp,  sp,  cr*cp]
  //
  // Verified:
  // Flat stationary:          0       + 0   + g    - g = 0 ✓
  // 90° roll right-side-down: -(-g)*1 + 0   + 0    - g = 0 ✓
  // 90° nose-up:              0       + g*1 + 0    - g = 0 ✓
  // Flat +1m/s² up:           0       + 0   +(g+1) - g = 1 ✓

  float R_world_up[3] = {
    -sr * cp, // body X component of world-up
     sp,      // body Y component of world-up
     cr * cp  // body Z component of world-up
  };

  float worldZ = R_world_up[0] * accelX
               + R_world_up[1] * accelY
               + R_world_up[2] * accelZ
               - GRAVITY_CON;

  velocity = 0.92f * (velocity + worldZ * dt) + 0.08f * ((baroAlt - height) / dt);
  height = 0.92f * (height + velocity * dt) + 0.08f * baroAlt;
}

void runPIDs() {
  rollInput = roll;
  pitchInput = pitch;
  yawRateInput = yawRate * GYRO_SCALE;
  altInput = height;

  pidRoll.Compute();
  pidPitch.Compute();
  pidYawRate.Compute();
  pidAlt.Compute();
}

void mixAndWriteMotors() {
  static const float motorScale[4] = {
    (motorMax - motorMin[0]) / 1000.0f,
    (motorMax - motorMin[1]) / 1000.0f,
    (motorMax - motorMin[2]) / 1000.0f,
    (motorMax - motorMin[3]) / 1000.0f
  };

  float throttle;
  if (altitudeHoldEnabled) {
    throttle = constrain(altOutput + 1500, 1000, 2000);
  } else {
    throttle = constrain((rcThrottle / 1000.0f) * 800.0f + 1000.0f, 1000.0f, 1800.0f);
  }

  // Positive yawRateOutput increases CW motors (FL, RR) →
  // net CCW reaction torque → drone yaws right-to-left ✓
  float m1_raw = throttle - rollOutput + pitchOutput + yawRateOutput; // FL CW
  float m2_raw = throttle + rollOutput + pitchOutput - yawRateOutput; // FR CCW
  float m3_raw = throttle + rollOutput - pitchOutput + yawRateOutput; // RR CW
  float m4_raw = throttle - rollOutput - pitchOutput - yawRateOutput; // RL CCW

  float m1_scaled = motorMin[0] + (m1_raw - 1000.0f) * motorScale[0];
  float m2_scaled = motorMin[1] + (m2_raw - 1000.0f) * motorScale[1];
  float m3_scaled = motorMin[2] + (m3_raw - 1000.0f) * motorScale[2];
  float m4_scaled = motorMin[3] + (m4_raw - 1000.0f) * motorScale[3];

  m1 = (uint16_t)constrain(m1_scaled, motorMin[0], 2000);
  m2 = (uint16_t)constrain(m2_scaled, motorMin[1], 2000);
  m3 = (uint16_t)constrain(m3_scaled, motorMin[2], 2000);
  m4 = (uint16_t)constrain(m4_scaled, motorMin[3], 2000);

  writeESC(ESC1, m1);
  writeESC(ESC2, m2);
  writeESC(ESC3, m3);
  writeESC(ESC4, m4);
}

// ────────────────────────────────────────────────────────────────
// UTILITY / OUTPUT FUNCTIONS
// ────────────────────────────────────────────────────────────────
void stopMotors() {
  writeESC(ESC1, (uint16_t) 1000);
  writeESC(ESC2, (uint16_t) 1000);
  writeESC(ESC3, (uint16_t) 1000);
  writeESC(ESC4, (uint16_t) 1000);
}

void writeESC(uint8_t pin, uint16_t us) {
  us = (uint16_t) constrain(us, 800, 2200);
  uint32_t duty = (uint32_t) ((us * 65535UL) / 20000UL);
  ledcWrite(pin, duty);
}

void buzzerAlert(int count, int duration_ms, int freq, int pause_ms, uint8_t priority) {
  if (buzzer.active && priority < buzzer.priority) return;

  noTone(BUZZER_PIN);
  buzzer.active = true;
  buzzer.beepsRemaining = count;
  buzzer.frequency = freq;
  buzzer.duration_ms = duration_ms;
  buzzer.pause_ms = pause_ms;
  buzzer.continuous = false;
  buzzer.priority = priority;
  buzzer.isTone = false;
  buzzer.lastToggle = millis();
}

void buzzerAlertContinuous(int freq, int duration_ms, int pause_ms, uint8_t priority) {
  if (buzzer.active && priority < buzzer.priority) return;

  noTone(BUZZER_PIN);
  buzzer.active = true;
  buzzer.beepsRemaining = 0;
  buzzer.frequency = freq;
  buzzer.duration_ms = duration_ms;
  buzzer.pause_ms = pause_ms;
  buzzer.continuous = true;
  buzzer.priority = priority;
  buzzer.isTone = false;
  buzzer.lastToggle = millis();
}

void buzzerStop() {
  noTone(BUZZER_PIN);
  buzzer.active = false;
  buzzer.isTone = false;
  buzzer.beepsRemaining = 0;
  buzzer.continuous = false;
  buzzer.priority = 0;
}

void updateBuzzer() {
  if (!buzzer.active) return;

  unsigned long now = millis();
  unsigned long elapsed = now - buzzer.lastToggle;

  if (!buzzer.isTone) {
    // Waiting for next beep start (pause phase)
    if (elapsed >= (unsigned long)buzzer.pause_ms) {
      tone(BUZZER_PIN, buzzer.frequency);
      buzzer.isTone = true;
      buzzer.lastToggle = now;
    }
  } else {
    // Beep is playing
    if (elapsed >= (unsigned long)buzzer.duration_ms) {
      noTone(BUZZER_PIN);
      buzzer.isTone = false;
      buzzer.lastToggle = now;

      // If finite sequence, count down
      if (!buzzer.continuous && buzzer.beepsRemaining > 0) {
        buzzer.beepsRemaining--;
        if (buzzer.beepsRemaining <= 0) {
          buzzer.active = false;
        }
      }
    }
  }
}

void updateLEDs() {
  unsigned long now = millis();

  digitalWrite(LED_ARMED, armed ? HIGH : LOW);
  digitalWrite(LED_ALTHOLD, altitudeHoldEnabled ? HIGH : LOW);

  static unsigned long lastFsBlink = 0;
  static bool fsBlinkState = false;
  if (receiverFailsafeActive) {
    if (now - lastFsBlink > 150) {
      fsBlinkState = !fsBlinkState;
      digitalWrite(LED_FAILSAFE, fsBlinkState);
      lastFsBlink = now;
    }
  } else {
    fsBlinkState = false;
    digitalWrite(LED_FAILSAFE, LOW);
  }

  static unsigned long lastLbBlink = 0;
  static bool lbBlinkState = false;
  if (lowBatCutoff) {
    digitalWrite(LED_LOWBAT, HIGH);
    lbBlinkState = true;
  } else if (lowBatWarning) {
    if (now - lastLbBlink > 200) {
      lbBlinkState = !lbBlinkState;
      digitalWrite(LED_LOWBAT, lbBlinkState);
      lastLbBlink = now;
    }
  } else {
    lbBlinkState = false;
    digitalWrite(LED_LOWBAT, LOW);
  }
}

void debugOutput() {
  if (!debugOutputEnabled) return;

  static unsigned long lastPrint = 0;
  if (millis() - lastPrint < 250) return;
  lastPrint = millis();

  float loopHz = (global_dt > 0.0001f) ? (1.0f / global_dt) : 0.0f;

  Serial.printf("Arm:%d Hold:%d FSafe:%d | R:%.1f P:%.1f H:%.2f Thr:%.0f SP:%.2f VBat:%.2f | M1:%u M2:%u M3:%u M4:%u | dt:%.1f ms Loop: %.1f Hz\n",
                armed, altitudeHoldEnabled, receiverFailsafeActive,
                roll, pitch, height,
                altitudeHoldEnabled
                  ? (float)(altOutput + 1500)
                  : constrain((rcThrottle / 1000.0f) * 800.0f + 1000.0f, 1000.0f, 1800.0f),
                altSetpoint, vbat, m1, m2, m3, m4, global_dt * 1000.0f, loopHz);
}

// ────────────────────────────────────────────────────────────────
// HTTP TELEMETRY SERVER
// ────────────────────────────────────────────────────────────────
void handleData() {
  static float prevRollRate = 0, prevPitchRate = 0, prevYawRate_s = 0;
  static float rotAccRoll = 0, rotAccPitch = 0, rotAccYaw = 0;

  // ── RC snapshot — read directly from shared vars under rcMutex ──
  // Avoids race with Core 1 readReceiver() which writes pwm* outside dataMutex
  uint16_t l_pwmRoll, l_pwmPitch, l_pwmThrottle;
  uint16_t l_pwmYaw, l_pwmArm, l_pwmAux;

  xSemaphoreTake(rcMutex, portMAX_DELAY);
  l_pwmRoll = sharedPwmRoll;
  l_pwmPitch = sharedPwmPitch;
  l_pwmThrottle = sharedPwmThrottle;
  l_pwmYaw = sharedPwmYaw;
  l_pwmArm = sharedPwmArm;
  l_pwmAux = sharedPwmAux;
  xSemaphoreGive(rcMutex);

  // ── Flight data snapshot — under dataMutex ──
  xSemaphoreTake(dataMutex, portMAX_DELAY);
  float l_roll = roll;
  float l_pitch = pitch;
  float l_yawRate = yawRate;
  float l_height = height;
  float l_velocity = velocity;
  float l_accelX = accelX;
  float l_accelY = accelY;
  float l_accelZ = accelZ;
  float l_gyroRoll = gyroRollRate;
  float l_gyroPitch = gyroPitchRate;
  float l_vbat = vbat;
  float l_dt = global_dt;
  bool l_armed = armed;
  bool l_altHold = altitudeHoldEnabled;
  bool l_failsafe = receiverFailsafeActive;
  bool l_lowBatCutoff = lowBatCutoff;
  bool l_lowBatWarning = lowBatWarning;
  float l_temperature = temperature;
  double l_altSetpoint = altSetpoint;
  uint16_t l_m1 = m1;
  uint16_t l_m2 = m2;
  uint16_t l_m3 = m3;
  uint16_t l_m4 = m4;
  xSemaphoreGive(dataMutex);

  if (l_dt > 0.001f) {
    rotAccRoll = 0.7f * rotAccRoll + 0.3f * ((l_gyroRoll - prevRollRate) / l_dt) * GYRO_SCALE;
    rotAccPitch = 0.7f * rotAccPitch + 0.3f * ((l_gyroPitch - prevPitchRate) / l_dt) * GYRO_SCALE;
    rotAccYaw = 0.7f * rotAccYaw + 0.3f * ((l_yawRate - prevYawRate_s) / l_dt) * GYRO_SCALE;
  }
  prevRollRate = l_gyroRoll;
  prevPitchRate = l_gyroPitch;
  prevYawRate_s = l_yawRate;

  char json[1280];
  int written = snprintf(json, sizeof(json),
    "{"
    "\"timestamp\":%lu,"
    "\"rcRoll\":%u,\"rcPitch\":%u,\"rcThrottle\":%u,\"rcYaw\":%u,\"rcArm\":%u,\"rcAux\":%u,"
    "\"roll\":%.2f,\"pitch\":%.2f,\"yawRate\":%.2f,"
    "\"height\":%.2f,\"velocity\":%.2f,"
    "\"accelX\":%.2f,\"accelY\":%.2f,\"accelZ\":%.2f,"
    "\"rotVelRoll\":%.2f,\"rotVelPitch\":%.2f,\"rotVelYaw\":%.2f,"
    "\"rotAccRoll\":%.2f,\"rotAccPitch\":%.2f,\"rotAccYaw\":%.2f,"
    "\"temperature\":%.2f,"
    "\"vbat\":%.2f,"
    "\"altSetpoint\":%.2f,"
    "\"m1\":%u,\"m2\":%u,\"m3\":%u,\"m4\":%u,"
    "\"armed\":%s,\"altitudeHoldEnabled\":%s,"
    "\"failsafe\":%s,\"lowBatCutoff\":%s,\"lowBatWarning\":%s"
    "}",
    millis(),
    l_pwmRoll, l_pwmPitch, l_pwmThrottle, l_pwmYaw, l_pwmArm, l_pwmAux,
    l_roll, l_pitch, l_yawRate * GYRO_SCALE,
    l_height, l_velocity,
    l_accelX, l_accelY, l_accelZ,
    l_gyroRoll * GYRO_SCALE,
    l_gyroPitch * GYRO_SCALE,
    l_yawRate * GYRO_SCALE,
    rotAccRoll, rotAccPitch, rotAccYaw,
    l_temperature,
    l_vbat,
    l_altSetpoint,
    l_m1, l_m2, l_m3, l_m4,
    l_armed ? "true" : "false",
    l_altHold ? "true" : "false",
    l_failsafe ? "true" : "false",
    l_lowBatCutoff ? "true" : "false",
    l_lowBatWarning ? "true" : "false"
  );

  if (written >= (int)sizeof(json))
    Serial.println("WARNING: JSON buffer too small, output truncated!");

  server.send(200, "application/json", json);
}

void handleRoot() {
  static const char html[] = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Quad Telemetry</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; background: #111; color: #0f0; padding: 16px; }

    h1 { font-size: 1.3em; color: #0f0; margin-bottom: 4px; }
    p.sub { color: #555; font-size: 0.85em; margin-bottom: 16px; }

    /* ── Grid layout ─────────────────────────────────── */
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 12px;
      margin-bottom: 16px;
    }

    .card {
      background: #1a1a1a;
      border: 1px solid #2a2a2a;
      border-radius: 8px;
      padding: 12px 14px;
    }
    .card h2 {
      font-size: 0.8em;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #555;
      margin-bottom: 10px;
    }

    /* ── RC Sliders ──────────────────────────────────── */
    .rc-row {
      display: flex;
      align-items: center;
      margin-bottom: 8px;
      gap: 8px;
    }
    .rc-label {
      width: 72px;
      font-size: 0.82em;
      color: #0a0;
      flex-shrink: 0;
    }
    .rc-track {
      flex: 1;
      height: 8px;
      background: #222;
      border-radius: 4px;
      position: relative;
    }
    /* Centre marker */
    .rc-track::after {
      content: '';
      position: absolute;
      left: 50%;
      top: -2px;
      width: 1px;
      height: 12px;
      background: #333;
    }
    .rc-fill {
      position: absolute;
      height: 100%;
      background: #0f0;
      border-radius: 4px;
      transition: left 0.08s, width 0.08s;
    }
    .rc-thumb {
      position: absolute;
      width: 10px;
      height: 10px;
      background: #0f0;
      border-radius: 50%;
      top: -1px;
      transform: translateX(-50%);
      transition: left 0.08s;
      box-shadow: 0 0 4px #0f06;
    }
    .rc-value {
      width: 38px;
      font-size: 0.78em;
      text-align: right;
      color: #0a0;
      flex-shrink: 0;
    }

    /* Throttle is unipolar — fill from left */
    .rc-fill.unipolar {
      left: 0 !important;
    }

    /* ── Attitude ────────────────────────────────────── */
    .att-row {
      display: flex;
      align-items: center;
      margin-bottom: 8px;
      gap: 8px;
    }
    .att-label { width: 52px; font-size: 0.82em; color: #0a0; flex-shrink: 0; }
    .att-bar-wrap {
      flex: 1;
      height: 8px;
      background: #222;
      border-radius: 4px;
      position: relative;
    }
    .att-bar-wrap::after {
      content: '';
      position: absolute;
      left: 50%;
      top: -2px;
      width: 1px;
      height: 12px;
      background: #333;
    }
    .att-fill {
      position: absolute;
      height: 100%;
      background: #0cf;
      border-radius: 4px;
      transition: left 0.08s, width 0.08s;
    }
    .att-thumb {
      position: absolute;
      width: 10px; height: 10px;
      background: #0cf;
      border-radius: 50%;
      top: -1px;
      transform: translateX(-50%);
      transition: left 0.08s;
      box-shadow: 0 0 4px #0cf6;
    }
    .att-value { width: 52px; font-size: 0.78em; text-align: right; color: #0aa; flex-shrink: 0; }

    /* ── Status indicators ───────────────────────────── */
    .status-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 8px;
    }
    .status-item {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 0.85em;
    }
    .led {
      width: 12px; height: 12px;
      border-radius: 50%;
      flex-shrink: 0;
      background: #222;
      border: 1px solid #333;
    }
    .led.on-green  { background: #0f0; box-shadow: 0 0 6px #0f08; border-color: #0f0; }
    .led.on-red    { background: #f00; box-shadow: 0 0 6px #f008; border-color: #f00; }
    .led.on-yellow { background: #ff0; box-shadow: 0 0 6px #ff08; border-color: #ff0; }
    .led.on-blue   { background: #0cf; box-shadow: 0 0 6px #0cf8; border-color: #0cf; }

    /* ── Gauges (height, vbat, temp) ─────────────────── */
    .gauge-row {
      display: flex;
      align-items: center;
      margin-bottom: 8px;
      gap: 8px;
    }
    .gauge-label { width: 68px; font-size: 0.82em; color: #0a0; flex-shrink: 0; }
    .gauge-track {
      flex: 1; height: 8px;
      background: #222; border-radius: 4px;
      position: relative; overflow: hidden;
    }
    .gauge-fill {
      position: absolute;
      left: 0; top: 0; height: 100%;
      border-radius: 4px;
      transition: width 0.15s;
    }
    .gauge-fill.green  { background: #0f0; }
    .gauge-fill.yellow { background: #ff0; }
    .gauge-fill.red    { background: #f00; }
    .gauge-fill.cyan   { background: #0cf; }
    .gauge-value { width: 52px; font-size: 0.78em; text-align: right; color: #0a0; flex-shrink: 0; }

    /* ── Motor bars ──────────────────────────────────── */
    .motor-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      text-align: center;
    }
    .motor-col { display: flex; flex-direction: column; align-items: center; gap: 4px; }
    .motor-bar-wrap {
      width: 24px; height: 80px;
      background: #222; border-radius: 4px;
      position: relative; overflow: hidden;
      display: flex; align-items: flex-end;
    }
    .motor-bar-fill {
      width: 100%;
      background: #0f0;
      border-radius: 4px;
      transition: height 0.08s;
      min-height: 2px;
    }
    .motor-label { font-size: 0.75em; color: #555; }
    .motor-value { font-size: 0.75em; color: #0a0; }

    /* ── Debug toggle ────────────────────────────────── */
    .debug-row { margin-bottom: 12px; display: flex; align-items: center; gap: 12px; }
    button {
      padding: 8px 20px; font-size: 0.9em;
      border: none; border-radius: 6px; cursor: pointer;
    }
    #toggleBtn.off { background: #222; color: #0f0; border: 1px solid #0f0; }
    #toggleBtn.on  { background: #0f0; color: #111; }
    #debugStatus   { font-size: 0.82em; color: #555; }

    /* ── Raw JSON ────────────────────────────────────── */
    details { margin-top: 12px; }
    summary { cursor: pointer; color: #555; font-size: 0.82em; margin-bottom: 6px; }
    pre {
      background: #1a1a1a; border: 1px solid #2a2a2a;
      padding: 12px; border-radius: 8px;
      font-size: 0.8em; overflow-x: auto;
      max-height: 300px; overflow-y: auto;
    }
  </style>
</head>
<body>

  <h1>ESP32 Quadcopter</h1>
  <p class="sub">QuadTelemetry &nbsp;·&nbsp; 192.168.4.1 &nbsp;·&nbsp; <span id="ts">--</span></p>

  <!-- Debug toggle -->
  <div class="debug-row">
    <button id="toggleBtn" class="off" onclick="toggleDebug()">Serial Debug: OFF</button>
    <span id="debugStatus"></span>
  </div>

  <div class="grid">

    <!-- ── RC Inputs ───────────────────────────────── -->
    <div class="card">
      <h2>RC Inputs</h2>

      <div class="rc-row">
        <span class="rc-label">Roll</span>
        <div class="rc-track" id="rc-roll-track">
          <div class="rc-fill" id="rc-roll-fill"></div>
          <div class="rc-thumb" id="rc-roll-thumb"></div>
        </div>
        <span class="rc-value" id="rc-roll-val">--</span>
      </div>

      <div class="rc-row">
        <span class="rc-label">Pitch</span>
        <div class="rc-track" id="rc-pitch-track">
          <div class="rc-fill" id="rc-pitch-fill"></div>
          <div class="rc-thumb" id="rc-pitch-thumb"></div>
        </div>
        <span class="rc-value" id="rc-pitch-val">--</span>
      </div>

      <div class="rc-row">
        <span class="rc-label">Yaw</span>
        <div class="rc-track" id="rc-yaw-track">
          <div class="rc-fill" id="rc-yaw-fill"></div>
          <div class="rc-thumb" id="rc-yaw-thumb"></div>
        </div>
        <span class="rc-value" id="rc-yaw-val">--</span>
      </div>

      <div class="rc-row">
        <span class="rc-label">Throttle</span>
        <div class="rc-track" id="rc-thr-track">
          <div class="rc-fill unipolar" id="rc-thr-fill"></div>
          <div class="rc-thumb" id="rc-thr-thumb"></div>
        </div>
        <span class="rc-value" id="rc-thr-val">--</span>
      </div>

      <div class="rc-row">
        <span class="rc-label">Arm (CH5)</span>
        <div class="rc-track">
          <div class="rc-fill unipolar" id="rc-arm-fill"></div>
          <div class="rc-thumb" id="rc-arm-thumb"></div>
        </div>
        <span class="rc-value" id="rc-arm-val">--</span>
      </div>

      <div class="rc-row">
        <span class="rc-label">AltHold (CH6)</span>
        <div class="rc-track">
          <div class="rc-fill unipolar" id="rc-aux-fill"></div>
          <div class="rc-thumb" id="rc-aux-thumb"></div>
        </div>
        <span class="rc-value" id="rc-aux-val">--</span>
      </div>
    </div>

    <!-- ── Attitude ─────────────────────────────────── -->
    <div class="card">
      <h2>Attitude</h2>

      <div class="att-row">
        <span class="att-label">Roll</span>
        <div class="att-bar-wrap">
          <div class="att-fill" id="att-roll-fill"></div>
          <div class="att-thumb" id="att-roll-thumb"></div>
        </div>
        <span class="att-value" id="att-roll-val">--</span>
      </div>

      <div class="att-row">
        <span class="att-label">Pitch</span>
        <div class="att-bar-wrap">
          <div class="att-fill" id="att-pitch-fill"></div>
          <div class="att-thumb" id="att-pitch-thumb"></div>
        </div>
        <span class="att-value" id="att-pitch-val">--</span>
      </div>

      <div class="att-row">
        <span class="att-label">Yaw Rate</span>
        <div class="att-bar-wrap">
          <div class="att-fill" id="att-yaw-fill"></div>
          <div class="att-thumb" id="att-yaw-thumb"></div>
        </div>
        <span class="att-value" id="att-yaw-val">--</span>
      </div>

      <div class="att-row">
        <span class="att-label">Height</span>
        <div class="att-bar-wrap">
          <div class="att-fill" id="att-height-fill" style="background:#0f0;"></div>
          <div class="att-thumb" id="att-height-thumb" style="background:#0f0; box-shadow:0 0 4px #0f06;"></div>
        </div>
        <span class="att-value" id="att-height-val">--</span>
      </div>

      <div class="att-row">
        <span class="att-label">Velocity</span>
        <div class="att-bar-wrap">
          <div class="att-fill" id="att-vel-fill"></div>
          <div class="att-thumb" id="att-vel-thumb"></div>
        </div>
        <span class="att-value" id="att-vel-val">--</span>
      </div>
    </div>

    <!-- ── Status LEDs ──────────────────────────────── -->
    <div class="card">
      <h2>Status</h2>
      <div class="status-grid">
        <div class="status-item">
          <div class="led" id="led-armed"></div>
          <span>Armed</span>
        </div>
        <div class="status-item">
          <div class="led" id="led-althold"></div>
          <span>Alt Hold</span>
        </div>
        <div class="status-item">
          <div class="led" id="led-failsafe"></div>
          <span>Failsafe</span>
        </div>
        <div class="status-item">
          <div class="led" id="led-lowbat"></div>
          <span>Low Battery</span>
        </div>
        <div class="status-item">
          <div class="led" id="led-cutoff"></div>
          <span>Bat Cutoff</span>
        </div>
      </div>

      <!-- Gauges -->
      <div style="margin-top:14px;">

        <div class="gauge-row">
          <span class="gauge-label">Battery</span>
          <div class="gauge-track">
            <div class="gauge-fill green" id="gauge-vbat"></div>
          </div>
          <span class="gauge-value" id="val-vbat">--</span>
        </div>

        <div class="gauge-row">
          <span class="gauge-label">Alt SP</span>
          <div class="gauge-track">
            <div class="gauge-fill cyan" id="gauge-altsp"></div>
          </div>
          <span class="gauge-value" id="val-altsp">--</span>
        </div>

        <div class="gauge-row">
          <span class="gauge-label">Temp</span>
          <div class="gauge-track">
            <div class="gauge-fill yellow" id="gauge-temp"></div>
          </div>
          <span class="gauge-value" id="val-temp">--</span>
        </div>

      </div>
    </div>

    <!-- ── Motors ───────────────────────────────────── -->
    <div class="card">
      <h2>Motors (µs)</h2>
      <div class="motor-grid">
        <div class="motor-col">
          <div class="motor-bar-wrap">
            <div class="motor-bar-fill" id="motor-1"></div>
          </div>
          <span class="motor-label">M1 FL</span>
          <span class="motor-value" id="motor-1-val">--</span>
        </div>
        <div class="motor-col">
          <div class="motor-bar-wrap">
            <div class="motor-bar-fill" id="motor-2"></div>
          </div>
          <span class="motor-label">M2 FR</span>
          <span class="motor-value" id="motor-2-val">--</span>
        </div>
        <div class="motor-col">
          <div class="motor-bar-wrap">
            <div class="motor-bar-fill" id="motor-3"></div>
          </div>
          <span class="motor-label">M3 RR</span>
          <span class="motor-value" id="motor-3-val">--</span>
        </div>
        <div class="motor-col">
          <div class="motor-bar-wrap">
            <div class="motor-bar-fill" id="motor-4"></div>
          </div>
          <span class="motor-label">M4 RL</span>
          <span class="motor-value" id="motor-4-val">--</span>
        </div>
      </div>
    </div>

  </div><!-- end grid -->

  <!-- Raw JSON -->
  <details>
    <summary>Raw JSON</summary>
    <pre id="raw">Loading...</pre>
  </details>

  <script>
    // ── Helpers ──────────────────────────────────────────────

    // Bipolar slider: value in [-range, +range], fills from centre
    function setBipolar(fillId, thumbId, value, range) {
      const pct   = Math.max(-1, Math.min(1, value / range));  // -1 to +1
      const mid   = 50;
      const halfW = Math.abs(pct) * 50;
      const fill  = document.getElementById(fillId);
      const thumb = document.getElementById(thumbId);
      if (!fill || !thumb) return;
      if (pct >= 0) {
        fill.style.left  = mid + '%';
        fill.style.width = halfW + '%';
      } else {
        fill.style.left  = (mid - halfW) + '%';
        fill.style.width = halfW + '%';
      }
      thumb.style.left = (mid + pct * 50) + '%';
    }

    // Unipolar slider: value in [min, max], fills from left
    function setUnipolar(fillId, thumbId, value, min, max) {
      const pct = Math.max(0, Math.min(1, (value - min) / (max - min)));
      const fill  = document.getElementById(fillId);
      const thumb = document.getElementById(thumbId);
      if (!fill || !thumb) return;
      fill.style.width = (pct * 100) + '%';
      thumb.style.left = (pct * 100) + '%';
    }

    // Motor bar: 1000–2000µs → 0–100% height
    function setMotor(barId, valId, us) {
      const pct = Math.max(0, Math.min(1, (us - 1000) / 1000));
      const bar = document.getElementById(barId);
      const val = document.getElementById(valId);
      if (bar) bar.style.height = (pct * 100) + '%';
      if (val) val.textContent = us;

      // Colour: green → yellow → red as throttle rises
      if (pct < 0.5)       bar.style.background = '#0f0';
      else if (pct < 0.75) bar.style.background = '#ff0';
      else                  bar.style.background = '#f80';
    }

    // Gauge: value in [min, max] → width %, colour thresholds optional
    function setGauge(gaugeId, valId, value, min, max, unit, threshYellow, threshRed) {
      const pct = Math.max(0, Math.min(1, (value - min) / (max - min)));
      const el  = document.getElementById(gaugeId);
      const vel = document.getElementById(valId);
      if (el) {
        el.style.width = (pct * 100) + '%';
        if (threshRed !== undefined && value <= threshRed)
          el.className = 'gauge-fill red';
        else if (threshYellow !== undefined && value <= threshYellow)
          el.className = 'gauge-fill yellow';
        else
          el.className = el.className.replace(/\b(red|yellow)\b/g, '').trim();
      }
      if (vel) vel.textContent = value.toFixed(2) + (unit || '');
    }

    function setLed(id, on, colour) {
      const el = document.getElementById(id);
      if (!el) return;
      el.className = 'led' + (on ? ' on-' + colour : '');
    }

    // ── Debug toggle ─────────────────────────────────────────
    let debugOn = false;

    fetch('/debug')
      .then(r => r.json())
      .then(d => setDebugState(d.debug));

    function toggleDebug() {
      fetch(debugOn ? '/debug/off' : '/debug/on')
        .then(r => r.json())
        .then(d => setDebugState(d.debug));
    }

    function setDebugState(state) {
      debugOn = state;
      const btn    = document.getElementById('toggleBtn');
      const status = document.getElementById('debugStatus');
      btn.textContent = 'Serial Debug: ' + (state ? 'ON' : 'OFF');
      btn.className   = state ? 'on' : 'off';
      status.textContent = state ? 'Printing every 250ms' : '';
    }

    // ── Telemetry poll ───────────────────────────────────────
    setInterval(() => {
      fetch('/data')
        .then(r => r.json())
        .then(d => {
          // Timestamp
          document.getElementById('ts').textContent =
            new Date().toLocaleTimeString();

          // ── RC inputs ──
          setBipolar ('rc-roll-fill',  'rc-roll-thumb',  d.rcRoll  - 1500, 500);
          setBipolar ('rc-pitch-fill', 'rc-pitch-thumb', d.rcPitch - 1500, 500);
          setBipolar ('rc-yaw-fill',   'rc-yaw-thumb',   d.rcYaw   - 1500, 500);
          setUnipolar('rc-thr-fill',   'rc-thr-thumb',   d.rcThrottle, 1000, 2000);
          setUnipolar('rc-arm-fill',   'rc-arm-thumb',   d.rcArm,  1000, 2000);
          setUnipolar('rc-aux-fill',   'rc-aux-thumb',   d.rcAux,  1000, 2000);

          document.getElementById('rc-roll-val').textContent  = d.rcRoll;
          document.getElementById('rc-pitch-val').textContent = d.rcPitch;
          document.getElementById('rc-yaw-val').textContent   = d.rcYaw;
          document.getElementById('rc-thr-val').textContent   = d.rcThrottle;
          document.getElementById('rc-arm-val').textContent   = d.rcArm;
          document.getElementById('rc-aux-val').textContent   = d.rcAux;

          // ── Attitude ──
          // Roll ±45°, Pitch ±45°, YawRate ±220°/s, Height 0–3m, Velocity ±2m/s
          setBipolar ('att-roll-fill',   'att-roll-thumb',   d.roll,     45);
          setBipolar ('att-pitch-fill',  'att-pitch-thumb',  d.pitch,    45);
          setBipolar ('att-yaw-fill',    'att-yaw-thumb',    d.yawRate, 220);
          setUnipolar('att-height-fill', 'att-height-thumb', d.height,   0,  3);
          setBipolar ('att-vel-fill',    'att-vel-thumb',    d.velocity, 2);

          document.getElementById('att-roll-val').textContent   = d.roll.toFixed(1)    + '°';
          document.getElementById('att-pitch-val').textContent  = d.pitch.toFixed(1)   + '°';
          document.getElementById('att-yaw-val').textContent    = d.yawRate.toFixed(1) + '°/s';
          document.getElementById('att-height-val').textContent = d.height.toFixed(2)  + 'm';
          document.getElementById('att-vel-val').textContent    = d.velocity.toFixed(2)+ 'm/s';

          // ── Status LEDs ──
          setLed('led-armed',    d.armed,          'green');
          setLed('led-althold',  d.altitudeHoldEnabled, 'blue');
          setLed('led-failsafe', d.failsafe,       'yellow');
          setLed('led-lowbat',   d.lowBatWarning,  'yellow');
          setLed('led-cutoff',   d.lowBatCutoff,   'red');

          // ── Gauges ──
          // Battery 9.0–12.6V, warn at 10.2, cutoff at 9.3
          setGauge('gauge-vbat',  'val-vbat',  d.vbat,        9.0, 12.6, 'V',  10.2, 9.3);
          setGauge('gauge-altsp', 'val-altsp', d.altSetpoint || 0, 0, 3, 'm');
          setGauge('gauge-temp',  'val-temp',  d.temperature, 10,  60,  '°C', null, null);

          // ── Motors ──
          setMotor('motor-1', 'motor-1-val', d.m1 || 1000);
          setMotor('motor-2', 'motor-2-val', d.m2 || 1000);
          setMotor('motor-3', 'motor-3-val', d.m3 || 1000);
          setMotor('motor-4', 'motor-4-val', d.m4 || 1000);

          // ── Raw JSON ──
          document.getElementById('raw').textContent =
            JSON.stringify(d, null, 2);
        })
        .catch(() => {
          document.getElementById('ts').textContent = 'reconnecting...';
        });
    }, 100);  // 100ms poll — smooth slider updates
  </script>
</body>
</html>
)rawliteral";

  server.send(200, "text/html", html);
}
